#!/bin/bash
# Fast workspace switching per monitor
# Dynamically assigns workspace offsets based on connected outputs

ACTION="$1"
WS_NUM="$2"

# Get mouse position
eval "$(xdotool getmouselocation --shell)"

# Get all active outputs sorted by position (left-to-right, top-to-bottom)
# and find which output the mouse pointer is on
OFFSET=0
i=0
while IFS= read -r line; do
    ox=$(echo "$line" | cut -d' ' -f1)
    oy=$(echo "$line" | cut -d' ' -f2)
    ow=$(echo "$line" | cut -d' ' -f3)
    oh=$(echo "$line" | cut -d' ' -f4)
    if (( X >= ox && X < ox + ow && Y >= oy && Y < oy + oh )); then
        OFFSET=$((i * 10))
        break
    fi
    ((i++))
done < <(i3-msg -t get_outputs | jq -r '.[] | select(.active) | "\(.rect.x) \(.rect.y) \(.rect.width) \(.rect.height)"' | sort -n -k1 -k2)

REAL_WS=$((OFFSET + WS_NUM))

if [[ "$ACTION" == "move" ]]; then
    exec i3-msg "move container to workspace number $REAL_WS; workspace number $REAL_WS"
else
    exec i3-msg "workspace number $REAL_WS"
fi
